apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql-service
spec:
  type: NodePort
  ports:
    - name: "3306"
      port: 3306
      nodePort : 30306
      targetPort: 3306
  selector:
    app: mysql
status:
  loadBalancer: {}
