class LengthConstant:
    BLOG_LENGTH = 150
    FACE_INDEX_LENGTH = 100
    ADDRESS_LENGTH = 250
    NAME_LENGTH = 50
    USERNAME_LENGTH = 20
    EMAIL_LENGTH = 50
    PHONE_LENGTH = 20
    TITLE_LENGTH = 100
    DESCRIPTION_LENGTH = 250
    META_LENGTH = 200
    BATCH_LENGTH = 50
    THANKS_MESSAGE_LENGTH = 500
    MESSAGE_LENGTH = 100

    ROWS_PER_PAGE = 3   
    ID_CARD_LENGTH = 8
    GENDER_LENGTH = 1

    MIN_NAME_LENGTH = 2
    MIN_CHI_NAME_LENGTH = 1
    

