version: '3.3'

services:
  web:
    image:
      itp4121projectdev.azurecr.io/itp4121project-main:9276825
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      FLASK_ENV: development
      DATABASE_HOST: mysql
      MAIL_SERVER: smtp4dev
      NGINX_PORT: 8080
      VAULT_URL: ${VAULT_URL}
      AZURE_CLIENT_ID: ${AZURE_CLIENT_ID}
      AZURE_TENANT_ID: ${AZURE_TENANT_ID}
      AZURE_CLIENT_SECRET: ${AZURE_CLIENT_SECRET}
    ports:
      - '80:5000'
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: dev_mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default_schema
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    cap_add:
      - SYS_NICE

