apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              #value: default_schema
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: tablename
            - name: MYSQL_PASSWORD
              #value: 123qweasd
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: password
            - name: MYSQL_ROOT_HOST
              value: '%'
            - name: MYSQL_ROOT_PASSWORD
              #value: 123qweasd
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: password
            - name: MYSQL_USER
              #value: itp4121admin
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: username
          image: mysql:5.7
          name: mysql-con
          ports:
            - containerPort: 3306
              name: mysql
status: {}
