apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: smtp4dev
  name: smtp4dev
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: smtp4dev
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: smtp4dev
    spec:
      containers:
        - env:
            - name: ServerOptions__Database
              value: /smtp4dev/database.db
            - name: ServerOptions__HostName
              value: smtp4dev
          image: rnwood/smtp4dev:v3
          name: smtp4dev
          ports:
            - containerPort: 80
            - containerPort: 25
            - containerPort: 143
          resources: {}
          volumeMounts:
            - mountPath: /smtp4dev
              name: smtp4dev-claim0
      restartPolicy: Always
      volumes:
        - name: smtp4dev-claim0
          persistentVolumeClaim:
            claimName: smtp4dev-claim0
status: {}
