apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
        - env:
            - name: AZURE_CLIENT_ID
            - name: AZURE_CLIENT_SECRET
            - name: AZURE_TENANT_ID
            - name: DATABASE_HOST
              value: mysql
            - name: FLASK_ENV
              value: development
            - name: MAIL_SERVER
              value: smtp4dev
            - name: NGINX_PORT
              value: "8080"
            - name: VAULT_URL
          image: web
          name: web
          ports:
            - containerPort: 5000
          resources: {}
          volumeMounts:
            - mountPath: /home/pc_donation/app
              name: web-claim0
            - mountPath: /home/pc_donation/logs
              name: web-claim1
      restartPolicy: Always
      volumes:
        - name: web-claim0
          persistentVolumeClaim:
            claimName: web-claim0
        - name: web-claim1
          persistentVolumeClaim:
            claimName: web-claim1
status: {}
