apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: smtp4dev
  name: smtp4dev
spec:
  ports:
    - name: "5002"
      port: 5002
      targetPort: 80
    - name: "25"
      port: 25
      targetPort: 25
    - name: "143"
      port: 143
      targetPort: 143
  selector:
    io.kompose.service: smtp4dev
status:
  loadBalancer: {}
